---
title: HoloRes - Development Team
author: Hololive Resort
email: hololiveresistance@yahoo.com
description: Hololive Resort's Development Team homepage and project overview.
baseurl: "/"
url: https://dev.hlresort.community
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
